---

name: Build Docker Image

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    environment: dockerhub-deploy

    strategy:
      matrix:
        include:
          - runner: ubuntu-24.04
            platform: linux/amd64

          - runner: ubuntu-24.04-arm
            platform: linux/arm64
    runs-on: ${{ matrix.runner }}
    outputs:
      digest-amd64: ${{ steps.set_outputs.outputs.digest-amd64 }}
      digest-arm64: ${{ steps.set_outputs.outputs.digest-arm64 }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set lower case owner name
        run: |
          echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
        env:
          OWNER: ${{ github.repository_owner }}

      - name: List files in context
        run: ls -al .

      - name: Build and push by digest
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: ${{ matrix.platform }}
          push: true
          build-args: |
            COMMIT_TAG=${{ github.sha }}
          outputs: |
            type=image,push-by-digest=true,name=stripedbees/autossh,push=true
          cache-from: type=gha,scope=${{ matrix.platform }}
          cache-to: type=gha,mode=max,scope=${{ matrix.platform }}
          provenance: false
      - name: Set outputs
        id: set_outputs
        run: |
          platform="${{ matrix.platform == 'linux/amd64' && 'amd64' || 'arm64' || 'armv8' || 'armv7' || 'armv6' }}"
          echo "digest-${platform}=${{ steps.build.outputs.digest }}" >> $GITHUB_OUTPUT

  merge_and_push:
    name: Create and Push Multi-arch Manifest
    needs: build
    environment: dockerhub-deploy
    runs-on: ubuntu-24.04
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set lower case owner name
        run: |
          echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
        env:
          OWNER: ${{ github.repository_owner }}

      - name: Create and push manifest
        run: |
          docker manifest create stripedbees/autossh:main \
            --amend stripedbees/autossh@${{ needs.build.outputs.digest-amd64 }} \
            --amend stripedbees/autossh@${{ needs.build.outputs.digest-arm64 }}
          docker manifest push stripedbees/autossh:main
